DROP TABLE IF EXISTS plants;

CREATE TABLE plants (
	id SERIAL PRIMARY KEY,
	name VARCHAR(100) UNIQUE NOT NULL,
	latin_name VARCHAR(200) UNIQUE NOT NULL,
	description VARCHAR(1000) NOT NULL,
	image_url VARCHAR(300) UNIQUE NOT NULL,
	water INTEGER NOT NULL,
    sun INTEGER NOT NULL,
    added_at DATE NOT NULL
);